projects: 
	- name : 'jQuery Plugins'
	  link : '/jQueryPlugins'
	  active : true
	  description : 'Collection of jQuery plugins'
	  language : 'Javascript'
	  platform : 'Web'
	- name : 'Convert To Encoding Tool'
	  link : '/ConvertToEncodingTool'
	  active : false
	  description : 'Library that converts the encoding of text based files (either per single file or per root folder). Filtering according to file extensions is also possible..'
	  languange : 'C#'
	  platform : 'Windows'
	