#Reset when committing!
usegoogleanalytics : true
#Reset when committing!
localmode : false
projects: 
  - name : 'jQuery Plugins'
    link : '/jQueryPlugins'
    description : 'Collection of jQuery plugins'
    language : 'Javascript'
    platform : 'Web'
    modified : 03-08-1999
    created : 03-05-2009  
  - name : 'ConvertToEncodingTool'
    link : '/ConvertToEncodingTool'
    description : 'Library that converts the encoding of text based files (either per single file or per root folder). Filtering according to file extensions is also possible..'
    language : 'C# (.NET 3.5)'
    platform : 'Desktop'
    modified : 18-07-1999
    created : 18-07-2009
#placeholder
templateforprojects:
  - name : 'jQuery Plugins1'
    link : '/jQueryPlugins1'
    description : 'Collecti1on of jQuery plugins'
    language : 'Javascript1'
    platform : 'Web1'
    modified : 03-08-1999
    created : 03-05-2009
  - name : 'jQuery Plugins2'
    link : '/jQueryPlugins2'
    description : 'Collecti21on of jQuery plugins'
    language : 'Javascript12'
    platform : 'Web12'
    modified : 03-08-1999
    created : 03-05-2009
