projects: 
  - name : 'jQuery Plugins'
    link : '/jQueryPlugins'  
    description : 'Collection of jQuery plugins'
    language : 'Javascript'
    platform : 'Web'
    modified : 03-08-1999
    created : 03-05-2009
